theme: jekyll-theme-cayman
title: Homepage
description: "kpr@informatik.un-kiel.de PhD Student at Kiel University, Computer Science. This page gives an overview about me and my projects."
author: Kai-Oliver Prott
